default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: face-to-face_development

test:
  <<: *default
  database: face-to-face_test

production:
  <<: *default
  database: face-to-face_production
