default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: face-to-face_development
  username: postgres
  password: postgres
  timeout: 5000


test:
  <<: *default
  database: face-to-face_test
  username: postgres
  password: postgres
  timeout: 5000


production:
  <<: *default
  database: face-to-face_production
